astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "google"
  model_name: "models/gemini-embedding-001"

retriever:
  top_k: 4

  llm:
    groq:
      provider: "groq"
      model_name: "qwen/qwen-3-32b"       # replaces llama-3.3-70b
      temperature: 0
      max_output_tokens: 2048

    google:
      provider: "google"
      model_name: "gemini-2.5-flash"
      temperature: 0
      max_output_tokens: 2048

    openai:
      provider: "openai"
      model_name: "gpt-4o-mini"
      temperature: 0
      max_output_tokens: 2048


